<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = '__root__';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'composer/package-versions-deprecated' => '1.11.99.5@b4f54f74ef3453349c24a845d22392cd31e65f1d',
  'doctrine/annotations' => '1.13.2@5b668aef16090008790395c02c893b1ba13f7e08',
  'doctrine/cache' => '2.1.1@331b4d5dbaeab3827976273e9356b3b453c300ce',
  'doctrine/collections' => '1.6.8@1958a744696c6bb3bb0d28db2611dc11610e78af',
  'doctrine/common' => '3.2.2@295082d3750987065912816a9d536c2df735f637',
  'doctrine/dbal' => '2.13.7@6e22f6012b42d7932674857989fcf184e9e9b1c3',
  'doctrine/deprecations' => 'v0.5.3@9504165960a1f83cc1480e2be1dd0a0478561314',
  'doctrine/doctrine-bundle' => '2.5.5@5c086cbbe5327937dd6f90da075f7d421b0f28bc',
  'doctrine/doctrine-migrations-bundle' => '2.2.3@0a081b55a88259a887af7be654743a8c5f703e99',
  'doctrine/event-manager' => '1.1.1@41370af6a30faa9dc0368c4a6814d596e81aba7f',
  'doctrine/inflector' => '1.4.4@4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
  'doctrine/instantiator' => '1.4.0@d56bf6102915de5702778fe20f2de3b2fe570b5b',
  'doctrine/lexer' => '1.2.2@9c50f840f257bbb941e6f4a0e94ccf5db5c3f76c',
  'doctrine/migrations' => '2.3.5@28d92a34348fee5daeb80879e56461b2e862fc05',
  'doctrine/orm' => '2.11.1@4b88ce787d3916c8366abf52f6c658a7a27ed3a6',
  'doctrine/persistence' => '2.3.0@f8af155c1e7963f3d2b4415097d55757bbaa53d8',
  'doctrine/sql-formatter' => '1.1.2@20c39c2de286a9d3262cc8ed282a4ae60e265894',
  'egulias/email-validator' => '2.1.25@0dbf5d78455d4d6a41d186da50adc1122ec066f4',
  'friendsofphp/proxy-manager-lts' => 'v1.0.5@006aa5d32f887a4db4353b13b5b5095613e0611f',
  'knplabs/knp-components' => 'v1.3.10@fc1755ba2b77f83a3d3c99e21f3026ba2a1429be',
  'knplabs/knp-paginator-bundle' => 'v4.1.1@ea6ac65818a734a9afaa05270e162506e726c184',
  'laminas/laminas-code' => '3.4.1@1cb8f203389ab1482bf89c0e70a04849bacd7766',
  'laminas/laminas-eventmanager' => '3.2.1@ce4dc0bdf3b14b7f9815775af9dfee80a63b4748',
  'laminas/laminas-zendframework-bridge' => '1.1.1@6ede70583e101030bcace4dcddd648f760ddf642',
  'markbaker/complex' => '1.5.0@c3131244e29c08d44fefb49e0dd35021e9e39dd2',
  'monolog/monolog' => '1.26.1@c6b00f05152ae2c9b04a448f99c7590beb6042f5',
  'phpdocumentor/reflection-common' => '2.1.0@6568f4687e5b41b054365f9ae03fcb1ed5f2069b',
  'phpdocumentor/reflection-docblock' => '4.3.4@da3fd972d6bafd628114f7e7e036f45944b62e9c',
  'phpdocumentor/type-resolver' => '1.0.1@2e32a6d48972b2c1976ed5d8967145b6cec4a4a9',
  'phpoffice/phpspreadsheet' => '1.5.2@cd60531c44f580fbdfbd55dfb935af791f09be5d',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.4@d49695b909c3b7628b6289db5479a1c204601f11',
  'psr/simple-cache' => '1.0.1@408d5eafb83c57f6365a3ca330ff23aa4a5fa39b',
  'sensio/framework-extra-bundle' => 'v5.5.7@6c0fa4e0e6dc3be90f7b40fa832aa47ec7dd801a',
  'symfony/asset' => 'v4.4.37@ca30ea16ff9c2917bc3d86796b940194f02985ae',
  'symfony/cache' => 'v4.4.37@7613787f68c5eaad98f0bd21d694e6d639b07bf0',
  'symfony/cache-contracts' => 'v1.1.11@41c956506500bea5502022f6be81da96fb9c7626',
  'symfony/config' => 'v4.4.37@e8c2d2c951ddedecb6d28954d336cb7d2e852d0e',
  'symfony/console' => 'v4.4.37@0259f01dbf9d77badddbbf4c2abb681f24c9cac6',
  'symfony/debug' => 'v4.4.37@5de6c6e7f52b364840e53851c126be4d71e60470',
  'symfony/dependency-injection' => 'v4.4.37@c00a23904b42f140087d36e1d22c88801bb39689',
  'symfony/deprecation-contracts' => 'v2.5.0@6f981ee24cf69ee7ce9736146d1c57c2780598a8',
  'symfony/doctrine-bridge' => 'v4.4.37@899a603d7edde120d7c0b26cafcbfdb5d10a5bbd',
  'symfony/dotenv' => 'v4.4.37@fcedd6d382b3afc3e1e786aa4e4fc4cf06f564cf',
  'symfony/error-handler' => 'v4.4.37@8d80ad881e1ce17979547873d093e3c987a6a629',
  'symfony/event-dispatcher' => 'v4.4.37@3ccfcfb96ecce1217d7b0875a0736976bc6e63dc',
  'symfony/event-dispatcher-contracts' => 'v1.1.11@01e9a4efac0ee33a05dfdf93b346f62e7d0e998c',
  'symfony/expression-language' => 'v4.4.37@b25f28d2bca785d0715426bdd4af873288fe1d89',
  'symfony/filesystem' => 'v4.4.37@c59f37705c3e513ae55b2735f128f4ce363c82ec',
  'symfony/finder' => 'v4.4.37@b17d76d7ed179f017aad646e858c90a2771af15d',
  'symfony/flex' => 'v1.18.3@d40a6b176b70ea323af2b08507319d1c417520fd',
  'symfony/form' => 'v4.4.37@e2d3b99a247e71dc3e3ff82c39ae6d5883dcd967',
  'symfony/framework-bundle' => 'v4.4.37@5ae3655a69ac8b6a7bf46ce2b1e04b7be2ec05c7',
  'symfony/http-client' => 'v4.4.37@8129ccd6233338e1d495b7734c003053766cb262',
  'symfony/http-client-contracts' => 'v1.1.11@8a497ee1712c2507eaccd31aca00dd603f93d25d',
  'symfony/http-foundation' => 'v4.4.37@27782a72399b92f44624f801adc5c28fb3f9d6c7',
  'symfony/http-kernel' => 'v4.4.37@ef830fb76eea90dc778fd68c8a7816fbc6109ed6',
  'symfony/inflector' => 'v4.4.37@e5e4c618a40e562d51757b54305bd113df59c29f',
  'symfony/intl' => 'v4.4.37@98e367e79b52962bca3c87b5469b3d08b295f3e1',
  'symfony/mailer' => 'v4.4.37@603703c41cc3765156b22143b7a585dd10e4cfb6',
  'symfony/mime' => 'v4.4.37@a4fb074827e59a80bc3c5df4657fa782bac7cdab',
  'symfony/monolog-bridge' => 'v4.4.37@152dcde5092b6fe034369f4a2dea05de38db9b79',
  'symfony/monolog-bundle' => 'v3.7.1@fde12fc628162787a4e53877abadc30047fd868b',
  'symfony/options-resolver' => 'v4.4.37@41d1e741a292574887629369400820c9645e8a87',
  'symfony/polyfill-intl-icu' => 'v1.24.0@c023a439b8551e320cc3c8433b198e408a623af1',
  'symfony/polyfill-intl-idn' => 'v1.24.0@749045c69efb97c70d25d7463abba812e91f3a44',
  'symfony/polyfill-intl-normalizer' => 'v1.24.0@8590a5f561694770bdcd3f9b5c69dde6945028e8',
  'symfony/polyfill-mbstring' => 'v1.24.0@0abb51d2f102e00a4eefcf46ba7fec406d245825',
  'symfony/polyfill-php72' => 'v1.24.0@9a142215a36a3888e30d0a9eeea9766764e96976',
  'symfony/polyfill-php73' => 'v1.24.0@cc5db0e22b3cb4111010e48785a97f670b350ca5',
  'symfony/polyfill-php80' => 'v1.24.0@57b712b08eddb97c762a8caa32c84e037892d2e9',
  'symfony/polyfill-php81' => 'v1.24.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f',
  'symfony/process' => 'v4.4.37@b2d924e5a4cb284f293d5092b1dbf0d364cb8b67',
  'symfony/property-access' => 'v4.4.37@28466f1248cdaa357c73cc835cda701bee258a1d',
  'symfony/property-info' => 'v4.4.37@cd9a8c2e3d19d4d4b9475e9d448cb4fbaee0e495',
  'symfony/proxy-manager-bridge' => 'v4.4.37@5ac73c41bdb6fa41139fa314dfbc4035bbcdebb2',
  'symfony/routing' => 'v4.4.37@324f7f73b89cd30012575119430ccfb1dfbc24be',
  'symfony/security-bundle' => 'v4.4.37@7000530d95d040dd0095b844191792644b4ccf3c',
  'symfony/security-core' => 'v4.4.37@77e11ed8d647608a45b7b93ed677761cceef2a7d',
  'symfony/security-csrf' => 'v4.4.37@45c956ef58135091f53732646a0acd28034f02c0',
  'symfony/security-guard' => 'v4.4.37@cf8922b164e1659726c8852663eaaa593eef668c',
  'symfony/security-http' => 'v4.4.37@d2edc6fc8974e81d83614092340e84d05ee15a58',
  'symfony/serializer' => 'v4.4.37@91a221aa75f5e47aa3a49267587b189cc33fbe5c',
  'symfony/service-contracts' => 'v1.1.11@633df678bec3452e04a7b0337c9bcfe7354124b3',
  'symfony/stopwatch' => 'v4.4.37@ad652049cc8d62417a33373f5d69edde4cbb29d5',
  'symfony/translation' => 'v4.4.37@4ce00d6875230b839f5feef82e51971f6c886e00',
  'symfony/translation-contracts' => 'v1.1.11@58ae23095ffdea045725dda70752566aa2908be6',
  'symfony/twig-bridge' => 'v4.4.37@ad832919f412e464bb099a1514c28d6d53223c76',
  'symfony/twig-bundle' => 'v4.4.37@7c32051cbe51e8fe922551fd298ec635d2dc7b52',
  'symfony/validator' => 'v4.4.37@e0af98b98085ed5307d0b85862763ef48b8d0220',
  'symfony/var-dumper' => 'v4.4.37@e74eee4ec02de71db3d60151aa5b203c990556df',
  'symfony/var-exporter' => 'v4.4.37@70efd494974592a6581ad44e962238e3f76baea4',
  'symfony/web-link' => 'v4.4.37@ab13621fd0c0119ad9ebc7179be7c5a1fc6a542d',
  'symfony/yaml' => 'v4.4.37@d7f637cc0f0cc14beb0984f2bb50da560b271311',
  'twig/extra-bundle' => 'v3.3.4@1fe52d84aa22b7891c7717ef904b1551c8d70100',
  'twig/twig' => 'v2.14.10@95fb194cd4dd6ac373a27af2bde2bad5d3f27aba',
  'webmozart/assert' => '1.9.1@bafc69caeb4d49c39fd0779086c03a3738cbb389',
  'myclabs/deep-copy' => '1.10.2@776f831124e9c62e1a2c601ecc52e776d8bb7220',
  'nikic/php-parser' => 'v4.13.2@210577fe3cf7badcc5814d99455df46564f3c077',
  'phar-io/manifest' => '1.0.3@7761fcacf03b4d4f16e7ccb606d4879ca431fcf4',
  'phar-io/version' => '2.0.1@45a2ec53a73c70ce41d55cedef9063630abaf1b6',
  'phpspec/prophecy' => 'v1.10.3@451c3cd1418cf640de218914901e51b064abb093',
  'phpunit/php-code-coverage' => '6.1.4@807e6013b00af69b6c5d9ceb4282d0393dbb9d8d',
  'phpunit/php-file-iterator' => '2.0.5@42c5ba5220e6904cbfe8b1a1bda7c0cfdc8c12f5',
  'phpunit/php-text-template' => '1.2.1@31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
  'phpunit/php-timer' => '2.1.3@2454ae1765516d20c4ffe103d85a58a9a3bd5662',
  'phpunit/php-token-stream' => '3.1.3@9c1da83261628cb24b6a6df371b6e312b3954768',
  'phpunit/phpunit' => '7.5.20@9467db479d1b0487c99733bb1e7944d32deded2c',
  'sebastian/code-unit-reverse-lookup' => '1.0.2@1de8cd5c010cb153fcd68b8d0f64606f523f7619',
  'sebastian/comparator' => '3.0.3@1071dfcef776a57013124ff35e1fc41ccd294758',
  'sebastian/diff' => '3.0.3@14f72dd46eaf2f2293cbe79c93cc0bc43161a211',
  'sebastian/environment' => '4.2.4@d47bbbad83711771f167c72d4e3f25f7fcc1f8b0',
  'sebastian/exporter' => '3.1.4@0c32ea2e40dbf59de29f3b49bf375176ce7dd8db',
  'sebastian/global-state' => '2.0.0@e8ba02eed7bbbb9e59e43dedd3dddeff4a56b0c4',
  'sebastian/object-enumerator' => '3.0.4@e67f6d32ebd0c749cf9d1dbd9f226c727043cdf2',
  'sebastian/object-reflector' => '1.1.2@9b8772b9cbd456ab45d4a598d2dd1a1bced6363d',
  'sebastian/recursion-context' => '3.0.1@367dcba38d6e1977be014dc4b22f47a484dac7fb',
  'sebastian/resource-operations' => '2.0.2@31d35ca87926450c44eae7e2611d45a7a65ea8b3',
  'sebastian/version' => '2.0.1@99732be0ddb3361e16ad77b68ba41efc8e979019',
  'symfony/browser-kit' => 'v4.4.37@6e81008cac62369871cb6b8de64576ed138e3998',
  'symfony/css-selector' => 'v4.4.37@0628e6c6d7c92f1a7bae543959bdc17347be2436',
  'symfony/debug-bundle' => 'v4.4.37@f21cce588be146c9111cb9041f0784a6534fd648',
  'symfony/dom-crawler' => 'v4.4.37@60d36408a3a48500bcc6e30d9f831e51d04d7fa4',
  'symfony/maker-bundle' => 'v1.36.4@716eee9c8b10b33e682df1b7d80b9061887e9691',
  'symfony/phpunit-bridge' => 'v6.0.3@81f5e8e453433e0182a49ca45d4734cb3a2f818f',
  'symfony/web-profiler-bundle' => 'v4.4.37@10c7660d46f6f87c4eb34a8dce89e7f5de2c5931',
  'theseer/tokenizer' => '1.1.3@11336f6f84e16a720dae9d8e6ed5019efa85a0f9',
  'paragonie/random_compat' => '2.*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  'symfony/polyfill-ctype' => '*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  'symfony/polyfill-iconv' => '*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  'symfony/polyfill-php71' => '*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  'symfony/polyfill-php70' => '*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  'symfony/polyfill-php56' => '*@f4a76ee4abf540a46eaf96e3069d114e64da2939',
  '__root__' => 'dev-master@f4a76ee4abf540a46eaf96e3069d114e64da2939',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!self::composer2ApiUsable()) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (self::composer2ApiUsable()) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }

    private static function composer2ApiUsable(): bool
    {
        if (!class_exists(InstalledVersions::class, false)) {
            return false;
        }

        if (method_exists(InstalledVersions::class, 'getAllRawData')) {
            $rawData = InstalledVersions::getAllRawData();
            if (count($rawData) === 1 && count($rawData[0]) === 0) {
                return false;
            }
        } else {
            $rawData = InstalledVersions::getRawData();
            if ($rawData === null || $rawData === []) {
                return false;
            }
        }

        return true;
    }
}
